version: '3.8'

services:
  psql:
    image: postgres
    container_name: "postgres"
    ports:
      - "5432:5432"
    env_file: .env
    volumes:
      - .deploy/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  app:
    container_name: 'hl'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - psql
